[package]
name = "step-stl-converter"
version = "0.1.0"
description = "Batch convert STEP and STP CAD files to STL locally."
authors = ["Keychron"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
